regions = [
    'Andalucía',
    'Aragón',
    'Asturias, Principado de',
    'Balears, Illes',
    'Canarias',
    'Cantabria',
    'Castilla y León',
    'Castilla-La%20Mancha',
    'Cataluña',
    'Comunitat Valenciana',
    'Extremadura',
    'Galicia',
    'Madrid, Comunidad de',
    'Murcia, Región de',
    'Navarra, Comunidad Foral de',
    'País Vasco',
    'Rioja, La',
    'Ceuta',
    'Melilla',
]

touristic_points = [
    'Vitoria-Gasteiz', 
    'Alfàs del Pi, l\'', 
    'Alicante/Alacant', 
    'Benidorm', 
    'Calp', 
    'Dénia', 
    'Jávea/Xàbia', 
    'Teulada', 
    'Torrevieja', 
    'Roquetas de Mar', 
    'Calvià', 
    'Palma', 
    'Barcelona', 
    'Castelldefels', 
    'Cáceres', 
    'Tarifa', 
    'Córdoba', 
    'Cuenca', 
    'Almuñécar', 
    'Capileira', 
    'Granada', 
    'Alpujarra de la Sierra', 
    'Iruela, La', 
    'Segura de la Sierra', 
    'Ezcaray', 
    'Madrid', 
    'Benalmádena', 
    'Fuengirola', 
    'Málaga', 
    'Marbella', 
    'Mijas', 
    'Nerja', 
    'Torremolinos', 
    'Cartagena', 
    'Mazarrón', 
    'San Javier', 
    'Pamplona/Iruña', 
    'Cudillero', 
    'Antigua', 
    'Mogán', 
    'Oliva', 
    'Pájara', 
    'San Bartolomé de Tirajana', 
    'Teguise', 
    'Tías', 
    'Yaiza', 
    'Adeje', 
    'Alajeró', 
    'Arona', 
    'Breña Baja', 
    'Frontera', 
    'Granadilla de Abona', 
    'Llanos de Aridane, Los', 
    'Paso, El', 
    'Puerto de la Cruz', 
    'San Miguel de Abona', 
    'San Sebastián de la Gomera', 
    'Santa Cruz de la Palma', 
    'Santiago del Teide, Tazacorte', 
    'Valle Gran Rey', 
    'Sevilla', 
    'Cullera', 
    'València', 
    'Zaragoza',
]

touristic_zones = [
    "Andalucía: Costa De Almería",
    "Andalucía: Costa De La Luz (Huelva)",
    "Andalucía: Costa De La Luz De Cádiz",
    "Andalucía: Costa Del Sol (Málaga)",
    "Andalucía: Costa Tropical (Granada)",
    "Asturias (Principado De): Costa Verde",
    "Cataluña: Cataluña Central",
    "Cataluña: Costa  Barcelona",
    "Cataluña: Costa  Barcelona 2015",
    "Cataluña: Costa  Barcelona 2016",
    "Cataluña: Costa Barcelona-Maresme",
    "Cataluña: Costa Brava",
    "Cataluña: Costa Daurada",
    "Cataluña: Costa Del Garraf",
    "Cataluña: Terres de l'Ebre",
    "Comunitat Valenciana: Costa Azahar",
    "Comunitat Valenciana: Costa Blanca",
    "Comunitat Valenciana: Costa de Castellón",
    "Comunitat Valenciana: Costa Valencia",
    "Extremadura: Norte de Extremadura",
    "Galicia: Rías Altas (A Coruña)",
    "Galicia: Rías Baixas (Pontevedra y A Coruña)",
    "Murcia (Región De): Costa Cálida",
    "P. Nacional Aigüestortes ",
    "P. Nacional de Sierra de Guadarrama",
    "P. Nacional Ordesa",
    "P. Nacional Sierra Nevada",
    "P. Natural Alt Pirineu",
    "P. Natural Cadí-Moixeró ",
    "P. Natural de los Aiguamolls de I'Empordá",
    "P. Natural Doñana",
    "P. Natural Los Alcornocales ",
    "P. Natural Serra Calderona ",
    "P. Natural Serra Calderon ",
    "P. Natural Sierra de Grazalema",
    "P. Natural Sierra de Hornachuelos",
    "P. Natural Sierra de las Nieves",
    "P. Natural Sierra Nevada ",
    "P. Natural Sierra y Cañones de Guara",
    "P. Natural Sierras de Cazorla, Segura y las Villas",
    "P. Natural Zona Volcánica de la Garrotxa ",
    "Pais Vasco: Costa Bizkaia",
    "Pais Vasco: Costa Guipuzkoa",
    "Pirineo Aragonés",
    "Pirineo Catalán",
    "Pirineo Navarro",
    "Pirineus",
]